### ISSUE TITLE
Touch events in iOS not working

### ISSUE THREAD

**Issue by hwroter** [pichfl/jquery.slidescroll#7]
On line 236 of slidescroll.js touchevent defaults are disabled with     event.preventDefault();

I commented this out and the plugin still seems to function properly and touch events are now working but I have not gone any further than that.

**Comment by pichfl** [comment]
Good catch. I wasn't expecting many other touch events in my use case, so I went too far with this. 
If you want to create a pull request for the fix, I'd be happy to merge it. If you can't, I'll push a fix as soon as I have time for it.

**Comment by pichfl** [comment]
Mr @danielhusar is awesome and made a fix for this.
